export const systemPort  = "http://192.168.1.178:1108/"
export const ProductEndPoint = `${systemPort}products`;
export const categoryEndPoint =`${systemPort}products/categories`;
export const specialCategoryEndPoint =`${systemPort}products/categories/`;
export const heroSectionEndPoint =`${systemPort}advertisements`;
export const vendorsEndPoint =`${systemPort}vendors`;
export const newsLatterEndPoint =`${systemPort}subscribe`;
export const filterListEndPoint =`${systemPort}products/filters`
export const logInEndPoint =`${systemPort}login`;
export const registreEndPoint =`${systemPort}register`;
export const logoutEndPoint =`${systemPort}logout`;