export const systemPort  = "http://192.168.1.178:1108/"
export const ProductEndPoint = `${systemPort}products`;
export const categoryEndPoint =`${systemPort}products/categories`;
export const specialCategoryEndPoint =`${systemPort}products/categories/`;
export const heroSectionEndPoint =`${systemPort}advertisements`;
export const vendorsEndPoint =`${systemPort}vendors`;
export const newsLatterEndPoint =`${systemPort}subscribe`;
export const filterListEndPoint =`${systemPort}products/filters`
export const logInEndPoint =`${systemPort}login`;
export const registreEndPoint =`${systemPort}register`;
export const logoutEndPoint =`${systemPort}logout`;
export const cartEndPoint= `${systemPort}products/cart`  
export const favoriteProductsEndPoint= `${systemPort}products/favorite`  ;
export const favoriteProductRemovingEndPoint= `${favoriteProductsEndPoint}/remove/`
export const addProductReviewEndPoint = `${ProductEndPoint}/review`;
export const userAddressesEndPoint = `${systemPort}address`;
export const orderEndPoint =`${systemPort}orders`;
export const reNewTokenEndPoint =`${systemPort}generate-token`;
export const forgrtPasswordEndPoint =`${systemPort}forgot`;
export const resetPasswordEndPoint =`${systemPort}reset`;
export const contactUsEndPoint =`${systemPort}contact-us`;
